# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: macos-latest



steps:

- task: MavenAuthenticate@0
  displayName: 'Maven Authenticate'
  inputs:
    artifactsFeeds: My-demo-Feed

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'sonar-cloud-sp'
    organization: 'suchkan'
    scannerMode: 'Other'
    projectKey: 'nnegi79_pipelines-java'
    projectName: 'pipelines-java.git'


- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: sonar:sonar package 


- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: "JaCoCo"
    summaryFileLocation: "$(System.DefaultWorkingDirectory)/**/site/jacoco/jacoco.xml"
    reportDirectory: "$(System.DefaultWorkingDirectory)/**/site/jacoco"
    failIfCoverageEmpty: true
    additionalCodeCoverageFiles: 
    
- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'

